vse: &term
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build:
    <<: *term
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      
workflows:
  version: 2.1
  build:
    jobs:
      - build
      
