- name: Deploy to EC2 - term
  hosts: localhost
  connection: local
  tasks:
    - name: Launch instance - term
      ec2:
        instance_type: t2.micro
        image: ami-085925f297f89fce1
        region: us-east-1
        key_name: presentation
        vpc_subnet_id: subnet-0c2ed72d
        assign_public_ip: 'yes'
        wait: 'yes'
        count: 1
        group: eshop
        # aws_access_key: '{{access_key}}'
        # aws_secret_key: '{{secret_key}}'
        # security_token: '{{session_token}}'
        aws_access_key: ASIAY3I3AAQOEXBRRNJE
        aws_secret_key: bAsxmTH75NqSKuJ89eO4rBuHRry8jPvy+6bk74pC
        security_token: FwoGZXIvYXdzEKX//////////wEaDEEL2ESNJhANir/7uyLBARpGlELnp00x1gEd22nbQEyK0uanhdnmTLO6Mi2CVcfZVuUntkni85Aku2PTJrz8mVdhsmE9TvjGVw+hT/Pd5834xJ4RWkKu3Aom8aC80H21+rmVMzjS8Kpvg6NSXDjc6UfhcWMF89IwFimRAm6nQg6GyqC1b4M69IplBvVfIl2JlSs4Z7/9oBPImfLqfj3XlLRium6OrvBbQzwlrC9h4bZHzAGosgO3NiNoiewDlsbz3jBvkLB5FRKGoAyEOFTIj6go0tKL9gUyLWbB3bnwtyx0C8eXXiIUmxj9leT4FZiyeWglZJLZRHaFSh06+EnbydCbgFP/+A==
      register: ec2
    - name: Add instance host to group
      add_host: 'hostname={{ item.public_dns_name }} groupname=launched'
      with_items: '{{ec2.instances}}'
    - name: Wait for SSH connection
      wait_for: 'host={{ item.public_dns_name }} port=22 delay=30 state=started'
      with_items: '{{ec2.instances}}'

- name: Configure EC2
  hosts: launched
  connection: ssh
  tasks:
    - name: Install docker - term
      apt:
        name: docker.io
        state: present
        update_cache: 'yes'
      become: 'yes'
    - service:
        name: docker
        state: started
        enabled: 'yes'
      become: 'yes'
    - name: Get project files from git
      git:
        repo: 'https://github.com/hrdyjan1/term-final.git'
        dest: ./app
    - name: Build docker with eshop
      shell: 'cd app && docker build -t myeshop:latest .'
      become: 'yes'
    - name: Run docker with eshop
      shell: 'docker run -p 80:3000 myeshop'
      async: 45
      poll: 10
      become: 'yes'
    - wait_for:
        port: 80
